packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  typescript: ^6.0.3
  tsx: ^4.19.0
  '@types/node': ^25.0.0
  zod: ^4.3.0
  eslint: ^10.2.1
  turbo: ^2.9.6
  typescript-eslint: ^8.58.2
  tsup: ^8.5.1
  jira.js: ^5.3.1
  marked: ^18.0.2
  fastify: ^5.8.5
  fastify-type-provider-zod: ^6.1.0
  '@fastify/swagger': ^9.7.0
  '@scalar/fastify-api-reference': ^1.52.6
  openapi-types: ^12.1.3
